import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1764569624168 implements MigrationInterface {
    name = 'Auto1764569624168'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`fk_products_seller\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`fk_favorites_product\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`fk_fav_owner\``);
        await queryRunner.query(`ALTER TABLE \`chatreads\` DROP FOREIGN KEY \`fk_cr_msg\``);
        await queryRunner.query(`ALTER TABLE \`chatreads\` DROP FOREIGN KEY \`fk_cr_room\``);
        await queryRunner.query(`ALTER TABLE \`chatreads\` DROP FOREIGN KEY \`fk_cr_user\``);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` DROP FOREIGN KEY \`fk_cm_conversation\``);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` DROP FOREIGN KEY \`fk_cm_sender\``);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` DROP FOREIGN KEY \`fk_receipt_msg\``);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` DROP FOREIGN KEY \`fk_receipt_user\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_users_deletedAt\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`ix_fav_owner_created\` ON \`favorites\``);
        await queryRunner.query(`DROP INDEX \`ix_fav_product_created\` ON \`favorites\``);
        await queryRunner.query(`DROP INDEX \`ux_fav_owner_product\` ON \`favorites\``);
        await queryRunner.query(`DROP INDEX \`IDX_delivery_memberships_userId\` ON \`delivery_memberships\``);
        await queryRunner.query(`DROP INDEX \`UQ_delivery_memberships_userId\` ON \`delivery_memberships\``);
        await queryRunner.query(`DROP INDEX \`ix_conv_a\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`ix_conv_b\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`uq_conv_pair\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`ix_cr_user\` ON \`chatreads\``);
        await queryRunner.query(`DROP INDEX \`ix_cr_user_updatedAt\` ON \`chatreads\``);
        await queryRunner.query(`DROP INDEX \`ix_cm_conv_createdAt\` ON \`conversationmessages\``);
        await queryRunner.query(`DROP INDEX \`ix_cm_sender\` ON \`conversationmessages\``);
        await queryRunner.query(`DROP INDEX \`ix_cr_user_msg\` ON \`chatreceipts\``);
        await queryRunner.query(`CREATE TABLE \`productImages\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`productId\` char(36) NOT NULL, \`url\` varchar(500) NOT NULL, \`ord\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`ix_pimg_product\` (\`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`email_verifications\` (\`id\` char(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`codeHash\` char(64) NOT NULL, \`expireAt\` datetime NOT NULL, \`remainingAttempts\` int NOT NULL DEFAULT '5', \`usedAt\` datetime NULL, \`lastSentAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_44e5cfea68f87243cad38bb1b1\` (\`email\`), INDEX \`IDX_11acb33369827a079881ca230b\` (\`expireAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` bigint NOT NULL, \`type\` enum ('FRIEND_REQUEST_RECEIVED', 'FRIEND_REQUEST_ACCEPTED', 'FRIEND_REQUEST_REJECTED', 'FRIEND_REQUEST_CANCELLED', 'UNFRIENDED') NOT NULL, \`payload\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`readAt\` datetime NULL, INDEX \`ix_notif_user_created\` (\`userId\`, \`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation_messages\` (\`id\` char(36) NOT NULL, \`conversation_id\` char(36) NOT NULL, \`sender_id\` char(36) NOT NULL, \`content\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`ix_cm_sender\` (\`sender_id\`), INDEX \`ix_cm_conv_created_id\` (\`conversation_id\`, \`created_at\`, \`id\`), INDEX \`ix_cm_conv_created\` (\`conversation_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`images\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`isDeliveryMember\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deliveryTransport\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`participantA\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`participantB\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`participant_a\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`participant_b\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`priceWon\` \`priceWon\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`updatedAt\` \`updatedAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`deletedAt\` \`deletedAt\` datetime(3) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`universityName\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`universityName\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`favorites\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`delivery_memberships\` CHANGE \`userId\` \`userId\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery_memberships\` ADD UNIQUE INDEX \`IDX_d803c3bb32575d5c215ed23ddc\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`id\` char(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` CHANGE \`lastReadMessageId\` \`lastReadMessageId\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`DROP INDEX \`ix_cm_conv_created_id\` ON \`conversationmessages\``);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` DROP COLUMN \`conversationId\``);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` ADD \`conversationId\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` CHANGE \`deliveredAt\` \`deliveredAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` CHANGE \`readAt\` \`readAt\` datetime(6) NULL`);
        await queryRunner.query(`CREATE INDEX \`ix_products_category\` ON \`products\` (\`category\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_products_status\` ON \`products\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_products_priceWon\` ON \`products\` (\`priceWon\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_products_createdAt\` ON \`products\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uq_fav_owner_product\` ON \`favorites\` (\`ownerUserId\`, \`productId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uq_conv_pair\` ON \`conversations\` (\`participant_a\`, \`participant_b\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_conv_created\` ON \`conversations\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_conv_b\` ON \`conversations\` (\`participant_b\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_conv_a\` ON \`conversations\` (\`participant_a\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_cm_conv_created_id\` ON \`conversationmessages\` (\`conversationId\`, \`createdAt\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`productImages\` ADD CONSTRAINT \`FK_8dcf36b93879109c44a4ab49b77\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_e40a1dd2909378f0da1f34f7bd6\` FOREIGN KEY (\`sellerId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_e40c40a231134ea0683c2e6554a\` FOREIGN KEY (\`ownerUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`FK_0c7bba48aac77ad13092685ba5b\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_memberships\` ADD CONSTRAINT \`FK_d803c3bb32575d5c215ed23ddc4\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_messages\` ADD CONSTRAINT \`FK_8e166abf2dd2ee28670e53e6803\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` ADD CONSTRAINT \`FK_50d746f0157f5fc5963808eb703\` FOREIGN KEY (\`roomId\`) REFERENCES \`chatrooms\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` ADD CONSTRAINT \`FK_e1e38737f2ea6d8a6bbc13c6f17\` FOREIGN KEY (\`messageId\`) REFERENCES \`chatMessages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` DROP FOREIGN KEY \`FK_e1e38737f2ea6d8a6bbc13c6f17\``);
        await queryRunner.query(`ALTER TABLE \`chatreads\` DROP FOREIGN KEY \`FK_50d746f0157f5fc5963808eb703\``);
        await queryRunner.query(`ALTER TABLE \`conversation_messages\` DROP FOREIGN KEY \`FK_8e166abf2dd2ee28670e53e6803\``);
        await queryRunner.query(`ALTER TABLE \`delivery_memberships\` DROP FOREIGN KEY \`FK_d803c3bb32575d5c215ed23ddc4\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_0c7bba48aac77ad13092685ba5b\``);
        await queryRunner.query(`ALTER TABLE \`favorites\` DROP FOREIGN KEY \`FK_e40c40a231134ea0683c2e6554a\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_e40a1dd2909378f0da1f34f7bd6\``);
        await queryRunner.query(`ALTER TABLE \`productImages\` DROP FOREIGN KEY \`FK_8dcf36b93879109c44a4ab49b77\``);
        await queryRunner.query(`DROP INDEX \`ix_cm_conv_created_id\` ON \`conversationmessages\``);
        await queryRunner.query(`DROP INDEX \`ix_conv_a\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`ix_conv_b\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`ix_conv_created\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`uq_conv_pair\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`uq_fav_owner_product\` ON \`favorites\``);
        await queryRunner.query(`DROP INDEX \`ix_products_createdAt\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`ix_products_priceWon\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`ix_products_status\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`ix_products_category\` ON \`products\``);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` CHANGE \`readAt\` \`readAt\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` CHANGE \`deliveredAt\` \`deliveredAt\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` DROP COLUMN \`conversationId\``);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` ADD \`conversationId\` varchar(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`ix_cm_conv_created_id\` ON \`conversationmessages\` (\`conversationId\`, \`createdAt\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` CHANGE \`lastReadMessageId\` \`lastReadMessageId\` char(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`id\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`delivery_memberships\` DROP INDEX \`IDX_d803c3bb32575d5c215ed23ddc\``);
        await queryRunner.query(`ALTER TABLE \`delivery_memberships\` CHANGE \`userId\` \`userId\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`favorites\` CHANGE \`createdAt\` \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deletedAt\` \`deletedAt\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`universityName\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`universityName\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`deletedAt\` \`deletedAt\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`priceWon\` \`priceWon\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`participant_b\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP COLUMN \`participant_a\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`participantB\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD \`participantA\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deliveryTransport\` varchar(30) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`isDeliveryMember\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`images\` text NULL`);
        await queryRunner.query(`DROP INDEX \`ix_cm_conv_created\` ON \`conversation_messages\``);
        await queryRunner.query(`DROP INDEX \`ix_cm_conv_created_id\` ON \`conversation_messages\``);
        await queryRunner.query(`DROP INDEX \`ix_cm_sender\` ON \`conversation_messages\``);
        await queryRunner.query(`DROP TABLE \`conversation_messages\``);
        await queryRunner.query(`DROP INDEX \`ix_notif_user_created\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_11acb33369827a079881ca230b\` ON \`email_verifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_44e5cfea68f87243cad38bb1b1\` ON \`email_verifications\``);
        await queryRunner.query(`DROP TABLE \`email_verifications\``);
        await queryRunner.query(`DROP INDEX \`ix_pimg_product\` ON \`productImages\``);
        await queryRunner.query(`DROP TABLE \`productImages\``);
        await queryRunner.query(`CREATE INDEX \`ix_cr_user_msg\` ON \`chatreceipts\` (\`userId\`, \`messageId\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_cm_sender\` ON \`conversationmessages\` (\`senderId\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_cm_conv_createdAt\` ON \`conversationmessages\` (\`conversationId\`, \`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_cr_user_updatedAt\` ON \`chatreads\` (\`userId\`, \`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_cr_user\` ON \`chatreads\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uq_conv_pair\` ON \`conversations\` (\`participantA\`, \`participantB\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_conv_b\` ON \`conversations\` (\`participantB\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_conv_a\` ON \`conversations\` (\`participantA\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_delivery_memberships_userId\` ON \`delivery_memberships\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_delivery_memberships_userId\` ON \`delivery_memberships\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`ux_fav_owner_product\` ON \`favorites\` (\`ownerUserId\`, \`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_fav_product_created\` ON \`favorites\` (\`productId\`, \`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`ix_fav_owner_created\` ON \`favorites\` (\`ownerUserId\`, \`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_users_deletedAt\` ON \`users\` (\`deletedAt\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` ADD CONSTRAINT \`fk_receipt_user\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`chatreceipts\` ADD CONSTRAINT \`fk_receipt_msg\` FOREIGN KEY (\`messageId\`) REFERENCES \`chatmessages\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` ADD CONSTRAINT \`fk_cm_sender\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`conversationmessages\` ADD CONSTRAINT \`fk_cm_conversation\` FOREIGN KEY (\`conversationId\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` ADD CONSTRAINT \`fk_cr_user\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` ADD CONSTRAINT \`fk_cr_room\` FOREIGN KEY (\`roomId\`) REFERENCES \`chatrooms\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`chatreads\` ADD CONSTRAINT \`fk_cr_msg\` FOREIGN KEY (\`lastReadMessageId\`) REFERENCES \`chatmessages\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`fk_fav_owner\` FOREIGN KEY (\`ownerUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`favorites\` ADD CONSTRAINT \`fk_favorites_product\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`fk_products_seller\` FOREIGN KEY (\`sellerId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
    }

}
