apiVersion: v1
kind: Service
metadata:
  name: kumeong-api
spec:
  selector:
    app: kumeong-api
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
