apiVersion: v1
kind: Service
metadata:
  name: kumeong-api
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  #   prometheus.io/port: "3000"
spec:
  selector:
    app: kumeong-api
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
