apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumeong-front
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: kumeong-front
  template:
    metadata:
      labels:
        app: kumeong-front
    spec:
      containers:
        - name: front
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}

          # ============================
          # ★ env.js 파일 마운트
          # ============================
          volumeMounts:
            - name: env-config
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5

      # ============================
      # ★ ConfigMap 볼륨
      # ============================
      volumes:
        - name: env-config
          configMap:
            name: kumeong-front-env