apiVersion: v1
kind: Service
metadata:
  name: kumeong-front
spec:
  selector:
    app: kumeong-front
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
