# -------------------------
# Global Values
# -------------------------
namespace: default

# -------------------------
# Backend API Settings
# -------------------------
backend:
  image:
    repository: gegujin/kumeong-api
    tag: "only-friend"
    pullPolicy: IfNotPresent

  replicaCount: 1
  port: 3000

  env:
    NODE_ENV: "production"

    # ⭐ only-friend 브랜치는 /api prefix 없음
    API_PREFIX: "/"
    API_VERSION: "1"

    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_USERNAME: "root"
    DB_PASSWORD: "jin20503*"
    DB_DATABASE: "kumeong_store"

    CORS_ORIGIN: "http://kumeong-front.local"
    PUBLIC_BASE_URL: "http://kumeong-api.local"

    JWT_ACCESS_SECRET: "access_secret"
    JWT_REFRESH_SECRET: "refresh_secret"

  uploads:
    enabled: true
    size: 1Gi

  ingress:
    enabled: false
    className: ""
    host: "api.example.com"
    path: /
    tls: false

# -------------------------
# Frontend Settings
# -------------------------
frontend:
  image:
    repository: gegujin/kumeong-front
    tag: "only-friend"
    pullPolicy: IfNotPresent

  replicaCount: 1
  port: 80

  ingress:
    enabled: false
    className: ""
    host: "front.example.com"
    path: /
    tls: false

# -------------------------
# MySQL Settings
# -------------------------
mysql:
  enabled: true
  image: "mysql:8"
  port: 3306

  rootPassword: "jin20503*"
  database: "kumeong_store"

  persistence:
    enabled: true
    size: 1Gi
    storageClass: "local-path"
